language: generic
jobs:
  include:
  - stage: test
    name: "copr build test"
    script:
      - export SPEC=iml-update-check.spec
      - docker run -it -e SPEC="$SPEC" -e LOCAL_ONLY="True" -v $(pwd):/build:rw imlteam/copr
      - ((`find _topdir/RPMS -name *.rpm | wc -l` > 0))
  - stage: cd
    name: "Continuous Deployment"
    script:
      - export OWNER=managerforlustre
      - export PROJECT=manager-for-lustre-devel
      - export PACKAGE=iml-update-check
      - export SPEC=iml-update-check.spec
      - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
  - stage: deploy-copr-r5.0
    name: "Copr deploy"
    script:
      - export OWNER=managerforlustre
      - export PROJECT=manager-for-lustre-5.0
      - export PACKAGE=iml-update-check
      - export SPEC=iml-update-check.spec
      - docker run -it -e PROD="true" -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
stages:
  - test
  - name: cd
    if: branch = master AND type = push AND fork = false
  - name: deploy-copr-r5.0
    if: branch =~ ^v\d+\.\d+\.\d+$
